disable generating move operations due to type ambiguity
22>..\..\/include/wx/propgrid/advprops.h(460): error : more than one user-defined conversion from "const wxVariant" to "wxDateTime" applies:
22>              function "wxDateTime::wxDateTime(double)"
22>              function "wxDateTime::wxDateTime(wxDateTime &&)"
22>            return m_value;
22>                   ^

Signed-off-by: Marian 'VooDooMan' Meravy <vdm113@gmail.com>